import 'local_prefs.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _dict = {
    'en': {
      'app_name': 'Patashala',
      'settings': 'Settings',
      'home_settings': 'Home Settings',
      'appearance': 'Appearance',
      'language': 'Language',
      'english': 'English',
      'telugu': 'Telugu',
      'dark_mode': 'Dark Mode',
      'bright_mode': 'Bright Mode',
      'welcome_back': 'Welcome Back',
      'streak_days': 'Streak: 5 days',
      'featured_topics': 'Featured Topics',
      'all_topics': 'All Topics',
      'browse_topics': 'Browse Trigonometry + Mensuration topics',
      'open_progress': 'Open Progress Dashboard',
      'learning_boost': 'Learning Boost',
      'show_hints': 'Show Formula Hints',
      'autoplay_visuals': 'Auto-play Visuals',
      'experience': 'Experience',
      'sound_effects': 'Sound Effects',
      'haptic_feedback': 'Haptic Feedback',
      'text_size': 'Text Size',
      'logout': 'Logout',
      'progress_dashboard': 'Progress Dashboard',
      'learning': 'Learning',
      'autoplay_animations': 'Auto-play Animations',
      'accessibility': 'Accessibility',
      'high_contrast': 'High Contrast UI',
      'reduce_motion': 'Reduce Motion',
      'app_section': 'App',
      'notifications': 'Notifications',
      'data_saver': 'Data Saver Mode',
      'animation_speed': 'Animation Speed',
      'top_learners': 'Top Learners',
      'login_title': 'Welcome Back',
      'login_subtitle': 'Login with username and password',
      'username': 'Username',
      'password': 'Password',
      'remember_me': 'Remember me',
      'login': 'Login',
      'create_account': 'Create Account',
      'forgot_password': 'Forgot Password?',
      'reading_notes': 'Reading Notes',
      'mini_quiz': 'Mini Quiz',
      'mark_complete': 'Mark Complete',
      'completed': 'Completed',
      'day_sunset': 'Day / Sunset',
      'sun_angle': 'Sun Angle',
      'building_height': 'Building Height',
      'shadow_formula': 'shadow = height / tan(θ)',
      'choose_subject': 'Choose Subject',
      'choose_topic_subject': 'Choose Topic - {subject}',
      'select_subject': 'Select a Subject',
      'subject_pick_desc':
          'Pick a subject to explore interactive visual learning.',
      'subject_maths': 'Maths',
      'subject_chemistry': 'Chemistry',
      'subject_physics': 'Physics',
      'maths_subtitle': 'Trigonometry + Mensuration',
      'chem_subtitle': 'Interactive chemistry labs (coming soon)',
      'physics_subtitle': 'Interactive physics simulations (coming soon)',
      'chem_coming': 'Chemistry topics are coming soon.',
      'physics_coming': 'Physics topics are coming soon.',
      'select_maths_hint': 'Select Maths to view available topics.',
      'subjects': 'Subjects',
      'filter_all': 'All',
      'filter_trigonometry': 'Trigonometry',
      'filter_mensuration': 'Mensuration',
    },
    'te': {
      'app_name': 'పాఠశాల',
      'settings': 'సెట్టింగ్స్',
      'home_settings': 'హోమ్ సెట్టింగ్స్',
      'appearance': 'రూపం',
      'language': 'భాష',
      'english': 'ఇంగ్లీష్',
      'telugu': 'తెలుగు',
      'dark_mode': 'డార్క్ మోడ్',
      'bright_mode': 'బ్రైట్ మోడ్',
      'welcome_back': 'మళ్లీ స్వాగతం',
      'streak_days': 'స్ట్రీక్: 5 రోజులు',
      'featured_topics': 'ప్రత్యేక అంశాలు',
      'all_topics': 'అన్ని అంశాలు',
      'browse_topics': 'ట్రిగోనోమెట్రీ + మెన్సురేషన్ అంశాలు చూడండి',
      'open_progress': 'ప్రగతి డాష్‌బోర్డ్ తెరవండి',
      'learning_boost': 'అభ్యాస సహాయం',
      'show_hints': 'సూత్ర సూచనలు చూపు',
      'autoplay_visuals': 'ఆటో ప్లే విజువల్స్',
      'experience': 'అనుభవం',
      'sound_effects': 'సౌండ్ ఎఫెక్ట్స్',
      'haptic_feedback': 'హాప్టిక్ ఫీడ్‌బ్యాక్',
      'text_size': 'పాఠ్య పరిమాణం',
      'logout': 'లాగౌట్',
      'progress_dashboard': 'ప్రగతి డాష్‌బోర్డ్',
      'learning': 'అభ్యాసం',
      'autoplay_animations': 'ఆటో ప్లే యానిమేషన్స్',
      'accessibility': 'అందుబాటు',
      'high_contrast': 'హై కాంట్రాస్ట్ UI',
      'reduce_motion': 'మోషన్ తగ్గింపు',
      'app_section': 'యాప్',
      'notifications': 'నోటిఫికేషన్స్',
      'data_saver': 'డేటా సేవర్ మోడ్',
      'animation_speed': 'యానిమేషన్ వేగం',
      'top_learners': 'టాప్ లెర్నర్స్',
      'login_title': 'మళ్లీ స్వాగతం',
      'login_subtitle': 'యూజర్ నేమ్, పాస్‌వర్డ్‌తో లాగిన్ అవ్వండి',
      'username': 'యూజర్ నేమ్',
      'password': 'పాస్‌వర్డ్',
      'remember_me': 'నన్ను గుర్తుంచుకో',
      'login': 'లాగిన్',
      'create_account': 'కొత్త ఖాతా',
      'forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'reading_notes': 'చదివే నోట్స్',
      'mini_quiz': 'మినీ క్విజ్',
      'mark_complete': 'పూర్తి చేశాను',
      'completed': 'పూర్తైంది',
      'day_sunset': 'పగలు / సన్‌సెట్',
      'sun_angle': 'సూర్య కోణం',
      'building_height': 'భవనం ఎత్తు',
      'shadow_formula': 'నీడ = ఎత్తు / tan(θ)',
      'choose_subject': 'విషయాన్ని ఎంచుకోండి',
      'choose_topic_subject': 'అంశాన్ని ఎంచుకోండి - {subject}',
      'select_subject': 'ఒక విషయం ఎంచుకోండి',
      'subject_pick_desc':
          'ఇంటరాక్టివ్ విజువల్ లెర్నింగ్ చూడటానికి విషయం ఎంచుకోండి.',
      'subject_maths': 'మాథ్స్',
      'subject_chemistry': 'కెమిస్ట్రీ',
      'subject_physics': 'ఫిజిక్స్',
      'maths_subtitle': 'ట్రిగోనోమెట్రీ + మెన్సురేషన్',
      'chem_subtitle': 'ఇంటరాక్టివ్ కెమిస్ట్రీ ల్యాబ్స్ (త్వరలో)',
      'physics_subtitle': 'ఇంటరాక్టివ్ ఫిజిక్స్ సిమ్యులేషన్స్ (త్వరలో)',
      'chem_coming': 'కెమిస్ట్రీ అంశాలు త్వరలో వస్తాయి.',
      'physics_coming': 'ఫిజిక్స్ అంశాలు త్వరలో వస్తాయి.',
      'select_maths_hint': 'అందుబాటులో ఉన్న అంశాలకు మాథ్స్‌ను ఎంచుకోండి.',
      'subjects': 'విషయాలు',
      'filter_all': 'అన్ని',
      'filter_trigonometry': 'ట్రిగోనోమెట్రీ',
      'filter_mensuration': 'మెన్సురేషన్',
    },
  };

  static String t(String key) {
    final lang = LocalPrefs.settingsNotifier.value.languageCode;
    final table = _dict[lang] ?? _dict['en']!;
    return table[key] ?? _dict['en']![key] ?? key;
  }
}
