TOPICS = [
    {
        "id": "trig-right-triangle",
        "subject": "Trigonometry",
        "title": "Right Triangle Basics",
        "description": "Move the angle slider to see how triangle sides change.",
        "engine": "trig",
        "visualization_key": "right_triangle",
        "icon": "change_history",
        "presets": [
            {"label": "Small Angle", "params": {"angle": 20, "hypotenuse": 10}},
            {"label": "Balanced", "params": {"angle": 45, "hypotenuse": 10}},
            {"label": "Steep", "params": {"angle": 70, "hypotenuse": 10}},
        ],
    },
    {
        "id": "trig-sine-cosine",
        "subject": "Trigonometry",
        "title": "Sine and Cosine (Visual)",
        "description": "Understand sine and cosine with a rotating arm.",
        "engine": "trig",
        "visualization_key": "sine_cosine",
        "icon": "show_chart",
        "presets": [
            {"label": "30°", "params": {"angle": 30}},
            {"label": "90°", "params": {"angle": 90}},
            {"label": "210°", "params": {"angle": 210}},
        ],
    },
    {
        "id": "trig-angle-rotation",
        "subject": "Trigonometry",
        "title": "Angle Rotation",
        "description": "Rotate an angle and track where the point moves.",
        "engine": "trig",
        "visualization_key": "angle_rotation",
        "icon": "rotate_right",
        "presets": [
            {"label": "Quarter Turn", "params": {"angle": 90}},
            {"label": "Half Turn", "params": {"angle": 180}},
            {"label": "Full Turn", "params": {"angle": 360}},
        ],
    },
    {
        "id": "trig-shadow-length",
        "subject": "Trigonometry",
        "title": "Shadow Length Simulation",
        "description": "Change sun angle and see shadow length updates.",
        "engine": "trig",
        "visualization_key": "shadow_length",
        "icon": "wb_sunny",
        "presets": [
            {"label": "Morning", "params": {"sun_angle": 20, "object_height": 6}},
            {"label": "Noon", "params": {"sun_angle": 70, "object_height": 6}},
            {"label": "Tall Object", "params": {"sun_angle": 40, "object_height": 10}},
        ],
    },
    {
        "id": "mens-rectangle-area",
        "subject": "Mensuration",
        "title": "Area of Rectangle",
        "description": "Resize length and width using grid blocks.",
        "engine": "mensuration",
        "visualization_key": "rectangle_area",
        "icon": "crop_landscape",
        "presets": [
            {"label": "6 x 4", "params": {"length": 6, "width": 4}},
            {"label": "8 x 3", "params": {"length": 8, "width": 3}},
            {"label": "10 x 5", "params": {"length": 10, "width": 5}},
        ],
    },
    {
        "id": "mens-square-area",
        "subject": "Mensuration",
        "title": "Area of Square",
        "description": "Watch area change as side length changes.",
        "engine": "mensuration",
        "visualization_key": "square_area",
        "icon": "crop_square",
        "presets": [
            {"label": "Side 3", "params": {"side": 3}},
            {"label": "Side 6", "params": {"side": 6}},
            {"label": "Side 9", "params": {"side": 9}},
        ],
    },
    {
        "id": "mens-perimeter",
        "subject": "Mensuration",
        "title": "Perimeter of Shapes",
        "description": "Measure total boundary with sliders.",
        "engine": "mensuration",
        "visualization_key": "perimeter",
        "icon": "gesture",
        "presets": [
            {"label": "Rectangle", "params": {"shape": "rectangle", "length": 7, "width": 3}},
            {"label": "Wide", "params": {"shape": "rectangle", "length": 10, "width": 2}},
            {"label": "Square", "params": {"shape": "square", "side": 5}},
        ],
    },
    {
        "id": "mens-grid-area",
        "subject": "Mensuration",
        "title": "Area by Grid Method",
        "description": "Count full and half squares to estimate area.",
        "engine": "mensuration",
        "visualization_key": "grid_area",
        "icon": "grid_on",
        "presets": [
            {"label": "Simple Grid", "params": {"length": 5, "width": 4, "half_squares": 0}},
            {"label": "Mixed Grid", "params": {"length": 6, "width": 5, "half_squares": 4}},
            {"label": "Large Grid", "params": {"length": 8, "width": 6, "half_squares": 2}},
        ],
    },
]

TOPIC_BY_ID = {topic["id"]: topic for topic in TOPICS}
